name: Build and Deploy

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-test-deploy-template.yml
    with:
        buildConfig: "Debug"
        versionPrefix: ""
        versionSuffix: ""
    secrets:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}

