name: Build and Deploy (Alpha)

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-test-deploy-template.yml
    with:
        buildConfig: ${{ github.event.inputs.buildConfig }}
        versionPrefix: ${{ github.event.inputs.versionPrefix }}
        versionSuffix: ${{ github.event.inputs.versionSuffix }}
    secrets:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}


