name: Build Wiki

on:
  push:
    paths:
      # Trigger only when wiki directory changes
      - 'Help/**'
  workflow_dispatch:

jobs:
  build-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Config Environment Variables
      run: |
        /bin/bash ./build-scripts/setenv.sh
    - name: Run build script
      run: |
        /bin/bash ./build-scripts/build-wiki.sh -p "Jlw.Data.LocalizedContent" -b "Release" -u ${{ github.repository_owner }} -e ${{ secrets.GPR_EMAIL }} -t {{ env.GITHUB_TOKEN }}
  cleanup:
    needs: build-wiki
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Config Environment Variables
      run: |
        /bin/bash ./build-scripts/setenv.sh
    - name: Delete Artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        name: ${{ env.PKGNAME }}
        failOnError: false

