name: New Build and Deploy (Alpha)

on:
  workflow_dispatch:
    inputs:
        buildConfiguration:
            description: 'Build Configuration'
            required: true
            default: 'Debug'
            type: choice
            options:
            - Debug
            - Release

jobs:
  build-test-deploy:
    runs-on: windows-latest

    steps:
      - name: Set version number
        id: set-version-number
        run: |
          echo "{path}"
          