name: New Build and Deploy (Alpha)

on:
  workflow_dispatch:
    inputs:
        buildConfiguration:
            description: 'Build Configuration'
            required: true
            default: 'Debug'
            type: choice
            options:
            - Debug
            - Release

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Set version number
        id: set-version-number
        shell: pwsh
        run: |
          $buildVersion = Invoke-Expression "$env:GITHUB_WORKSPACE/build-scripts/set-version-property.ps1 ${{ inputs.buildConfiguration }}" -outvariable version
          echo "::export-variable name=BUILD_VERSION::$buildVersion"
          echo "::export-variable name=BUILD_VERSION2::Test2.1"
          echo "buildVersion : $buildVersion"
          echo "Version : $version"
      - name: Output environment variables
        id: show-env
        shell: pwsh
        run: |
          Invoke-Expression "dir env:"
          