name: New Build and Deploy (Alpha)

on:
  workflow_dispatch:
    inputs:
        buildconfig:
            description: 'Build Configuration'
            required: true
            default: 'Debug'
            type: string
        versionPrefix:
            description: 'Version Number'
            required: false
            default: ''
            type: string
        versionSuffix:
            description: 'Version Suffix'
            required: false
            default: ''
            type: string


jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      INPUT_VERSION_PREFIX: ${{ inputs.versionPrefix }}
      INPUT_VERSION_SUFFIX: ${{ github.event.inputs.versionSuffix }}
      INPUT_BUILD_CONFIG: ${{ github.event.inputs.buildconfig }}
    steps:
      - uses: actions/checkout@v3
      #- name: Setup dotnet
      #  uses: actions/setup-dotnet@v2
      #  with:
      #    dotnet-version: '6.x'
      #- uses: actions/cache@v3
      #  with:
      #    path: ~/.nuget/packages
      #    # Look to see if there is a cache hit for the corresponding requirements file
      #    key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      #    restore-keys: |
      #      ${{ runner.os }}-nuget
      - name: Set version number
        #shell: pwsh
        run: |
          Invoke-Expression "$env:GITHUB_WORKSPACE/build-scripts/set-version-property.ps1 '${{ inputs.buildConf }}' '${{ inputs.versionSuffix }}' '${{ inputs.versionPrefix }}' "
          #$echo "BUILD_VERSION=$vPrefix$vSuffix" 
          Write-Output "::export-variable name=BUILD_VERSION::$vPrefix$vSuffix"
        shell: pwsh
      - name: Output environment variables
        run: |
          Invoke-Expression "dir env:"
        shell: pwsh
          